jwt:
  secretKey: 4m6UYcQkl6OiU9pNH2VtCazv6el5ncm3bs7dJDfmd1k=

locale:
  timezone: Asia/Seoul

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Seoul
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/todolist
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:mysql://mysql:3306/tododb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    url: jdbc:mysql://host.docker.internal:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:p6spy:mysql://host.docker.internal:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: appuser
    password: appuser
  thymeleaf:
    cache: false
    #Pageable 기본 설정
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

mybatis:
  type-aliases-package: com.portfolio.main
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


jpa:
  hibernate:
    ddl-auto: validate #create create-drop, update, validate, none
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      highlight_sql: true
#      show_sql: true
#    org.hibernate.tool.hbm2ddl.SchemaUpdate:
#      format: true
#  #    open-in-view: false

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
#    org.mybatis: DEBUG
#    org.apache.ibatis: DEBUG
#    org.hibernate:
#      SQL: DEBUG
#      type: trace
#        descriptor:
#          sql: trace
