jwt:
  secretKey: 4m6UYcQkl6OiU9pNH2VtCazv6el5ncm3bs7dJDfmd1k=

locale:
  timezone: Asia/Seoul

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Seoul
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/todolist
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:mysql://mysql:3306/tododb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

#    AWS RDS
#    url: jdbc:p6spy:mysql://portfolio-mysql.c5d9lzbtvocn.ap-northeast-2.rds.amazonaws.com:3306/portfolio_db
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://portfolio-mysql.c5d9lzbtvocn.ap-northeast-2.rds.amazonaws.com:3306/portfolio_db
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://portfolio-mysql.c5d9lzbtvocn.ap-northeast-2.rds.amazonaws.com:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    docker
#    url: jdbc:p6spy:mysql://43.200.180.72:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: appuser
    password: appuser
  thymeleaf:
    cache: false
    #Pageable 기본 설정
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

mybatis:
  type-aliases-package: com.portfolio.main
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jpa:
  hibernate:
    ddl-auto: validate #create create-drop, update, validate, none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#      highlight_sql: false
#      show_sql: false
#    org.hibernate.tool.hbm2ddl.SchemaUpdate:
#      format: true
#  #    open-in-view: false

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.p6spy: DEBUG
