spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: appuser
    password: appuser
