jwt:
  secretKey: 4m6UYcQkl6OiU9pNH2VtCazv6el5ncm3bs7dJDfmd1k=

locale:
  timezone: Asia/Seoul

spring:
  profiles:
    active: local
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Seoul
  thymeleaf:
    cache: false
    #Pageable 기본 설정
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

mybatis:
  type-aliases-package: com.portfolio.main
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jpa:
  hibernate:
    ddl-auto: validate #create create-drop, update, validate, none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#      highlight_sql: false
#      show_sql: false
#    org.hibernate.tool.hbm2ddl.SchemaUpdate:
#      format: true
#  #    open-in-view: false

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.p6spy: DEBUG
